version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl properly...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name eks-ctl-hello

  build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f k8s/
