version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.ap-south-1.amazonaws.com/latest/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name eks-ctl-hello

  build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f k8s/
